Repository openshift/cluster-resource-override-admission-operator, pull requests merged in 2023-02, with the labels that each got.

#99 OCPBUGS-6101: Ensure operand image and version mismatch are reconciled
  pkg/clusterresourceoverride/internal/handlers/deploy.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#95 OCPNODE-1343: Selinux Workaround
  artifacts/example/selinux-fix-enable.yaml
  artifacts/example/test-namespace.yaml
  artifacts/example/test-selinux-pod.yaml
  artifacts/example/test-selinux-scc.yaml
  manifests/stable/clusterresourceoverride.crd.yaml
  pkg/apis/autoscaling/v1/override_types.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/generated/clientset/internalversion/clientset.go
  pkg/generated/clientset/internalversion/doc.go
  pkg/generated/clientset/internalversion/fake/clientset_generated.go
  pkg/generated/clientset/internalversion/fake/doc.go
  pkg/generated/clientset/internalversion/fake/register.go
  pkg/generated/clientset/internalversion/scheme/doc.go
  pkg/generated/clientset/internalversion/scheme/register.go
  pkg/generated/clientset/internalversion/typed/autoscaling/internalversion/autoscaling_client.go
  pkg/generated/clientset/internalversion/typed/autoscaling/internalversion/doc.go
  pkg/generated/clientset/internalversion/typed/autoscaling/internalversion/fake/doc.go
  pkg/generated/clientset/internalversion/typed/autoscaling/internalversion/fake/fake_autoscaling_client.go
  pkg/generated/clientset/internalversion/typed/autoscaling/internalversion/generated_expansion.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/autoscaling_client.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/clusterresourceoverride.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/doc.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/fake/doc.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/fake/fake_autoscaling_client.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/fake/fake_clusterresourceoverride.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1/generated_expansion.go
  pkg/generated/informers/externalversions/autoscaling/interface.go
  pkg/generated/informers/externalversions/autoscaling/v1/clusterresourceoverride.go
  pkg/generated/informers/externalversions/autoscaling/v1/interface.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/listers/autoscaling/v1/clusterresourceoverride.go
  pkg/generated/listers/autoscaling/v1/expansion_generated.go
Labels: lgtm, approved, jira/valid-reference

#101 add ppc64le arch label to CRO
  manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
Labels: lgtm, ok-to-test, approved

#104 Added s390x architecture label to operator CSV
  manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
Labels: lgtm, ok-to-test, approved

#103 Added SecurityContext settings to e2e dynamic test pod
  test/e2e/dynamic_test.go
Labels: lgtm, ok-to-test, approved
